/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerBindings` (hash: 212cb60b7a65b71c060bff6625330b34)
interface __BaseEnv_WorkerBindings {
	DB: D1Database;
	ASSETS: Fetcher;
	SUPABASE_URL: "https://staging-project-ref.supabase.co" | "http://127.0.0.1:15421";
	SUPABASE_JWT_ISSUER: "https://staging-project-ref.supabase.co/auth/v1" | "http://127.0.0.1:15421/auth/v1";
	SUPABASE_JWT_AUDIENCE: "authenticated";
	REPORT_GENERATOR: "rule_v1";
	APP_ENV: "staging" | "production";
	NON_PRODUCTION_TOOLS_ENABLED: "true" | "false";
	STAGING_ALLOWED_EMAILS: string | "";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		SUPABASE_URL: "https://staging-project-ref.supabase.co";
		SUPABASE_JWT_ISSUER: "https://staging-project-ref.supabase.co/auth/v1";
		SUPABASE_JWT_AUDIENCE: "authenticated";
		REPORT_GENERATOR: "rule_v1";
		APP_ENV: "staging";
		NON_PRODUCTION_TOOLS_ENABLED: "true";
		STAGING_ALLOWED_EMAILS: string;
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "SUPABASE_JWT_ISSUER" | "SUPABASE_JWT_AUDIENCE" | "REPORT_GENERATOR" | "APP_ENV" | "NON_PRODUCTION_TOOLS_ENABLED" | "STAGING_ALLOWED_EMAILS">> {}
}
