/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerBindings` (hash: 01819770851f532021f189102e308afd)
interface __BaseEnv_WorkerBindings {
	DB: D1Database;
	BROWSER: BrowserRun;
	ASSETS: Fetcher;
	SUPABASE_URL: string;
	SUPABASE_JWT_ISSUER: string;
	SUPABASE_JWT_AUDIENCE: string;
	REPORT_GENERATOR: string;
	APP_ENV: string;
	NON_PRODUCTION_TOOLS_ENABLED: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		DB: D1Database;
		BROWSER: BrowserRun;
		ASSETS: Fetcher;
		SUPABASE_URL: string;
		SUPABASE_JWT_ISSUER: string;
		SUPABASE_JWT_AUDIENCE: string;
		REPORT_GENERATOR: string;
		APP_ENV: string;
		NON_PRODUCTION_TOOLS_ENABLED: string;
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "SUPABASE_JWT_ISSUER" | "SUPABASE_JWT_AUDIENCE" | "REPORT_GENERATOR" | "APP_ENV" | "NON_PRODUCTION_TOOLS_ENABLED">> {}
}
